[run]
skip-files = ['routes/assets.go']

# TODO stylecheck once assets is annihilated.
[linters]
disable-all = true
enable = [
    'bodyclose',
    'deadcode',
    'depguard',
    'dogsled',
    'dupl',
  # 'funlen',
  # 'gochecknoglobals',
  # 'gochecknoinits',
  # 'gocognit',
  # 'goconst',
  # 'gocritic',
    'gocyclo',
  # 'godot',
  # 'godox',
    'goerr113',
    'gofmt',
    'goimports',
  # 'golint',
    'gomodguard',
  # 'gomnd',
    'goprintffuncname',
  # 'gosec',
    'gosimple',
    'govet',
    'ineffassign',
    'interfacer',
  # 'lll',
    'maligned',
    'misspell',
  # 'nakedret',
  # 'nestif',
    'nolintlint',
  # 'prealloc',
    'rowserrcheck',
  # 'scopelint',
    'staticcheck',
    'structcheck',
  # 'stylecheck',
  # 'testpackage',
    'typecheck',
    'unconvert',
    'unparam',
    'unused',
    'varcheck',
    'whitespace',
  # 'wsl',
]
