[run]
skip-files = ['routes/assets.go']

# SA1029 – Inappropriate key in call to context.WithValue
# https://staticcheck.io/docs/checks#SA1029
[[issues.exclude-rules]]
linters = 'staticcheck'
text    = 'SA1029:'

[linters-settings.misspell]
locale = 'UK'

# TODO noctx once github/ uses only github.com/shurcooL/githubv4.
[linters]
disable-all = true
enable = [
    'asciicheck',
    'bodyclose',
    'deadcode',
    'depguard',
    'dogsled',
    'dupl',
  # 'errcheck',
    'exhaustive',
    'exportloopref',
  # 'funlen',
    'gci',
  # 'gochecknoglobals',
  # 'gochecknoinits',
  # 'gocognit',
  # 'goconst',
  # 'gocritic',
  # 'gocyclo',
  # 'godot',
  # 'godox',
    'goerr113',
    'gofmt',
    'goheader',
    'gofumpt',
    'goimports',
  # 'golint',
    'gomodguard',
  # 'gomnd',
    'goprintffuncname',
  # 'gosec',
    'gosimple',
    'govet',
    'ineffassign',
    'interfacer',
  # 'lll',
    'maligned',
    'misspell',
  # 'nakedret',
  # 'nestif',
  # 'nlreturn',
  # 'noctx',
    'nolintlint',
  # 'prealloc',
    'rowserrcheck',
  # 'scopelint',
  # 'sqlclosecheck',
    'staticcheck',
    'structcheck',
    'stylecheck',
  # 'testpackage',
    'typecheck',
    'unconvert',
    'unparam',
    'unused',
    'varcheck',
    'whitespace',
  # 'wsl',
]
