[prune]
  go-tests        = true
  non-go          = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name   = "github.com/buildkite/terminal"

[[constraint]]
  branch = "master"
  name   = "github.com/julienschmidt/httprouter"

[[constraint]]
  branch = "master"
  name   = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name   = "github.com/pmezard/go-difflib"
