version: '2'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    cap_add:
      - CAP_KILL
      - CAP_SETGID
      - CAP_SETUID
      - CAP_SYS_ADMIN
    cap_drop:
      - ALL
    env_file: .env  # Used for testing with prod secrets, NEVER committed.
    environment:
      DEV:       1
      PGHOST:    db
      PGSSLMODE: disable
      PGUSER:    code-golf
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/go
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: code-golf
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../db:/docker-entrypoint-initdb.d
