version: '2'
services:
  app:
    ports:
      - 80:1080
      - 443:1443
  assets:
    image: alpine:3.13
    command:
      - ./esbuild
      - --watch
    user: 1000:1000
    volumes:
      - ..:/code-golf
    working_dir: /code-golf
  db:
    ports:
      - 5432:5432
