version: '2'
services:
  app:
    command:
      - go
      - run
      - .
    depends_on:
      - db
    environment:
      E2E: 1
    healthcheck:
      test:     curl -fks https://app:1443/healthz
      interval: 1s
      retries:  20
  db:
    tmpfs: /var/lib/postgresql/data
  e2e:
    depends_on:
      app:
        condition: service_healthy
      firefox:
        condition: service_started
    entrypoint:
      - prove6
      - -It
    environment:
      PGDATABASE: code-golf
      PGHOST:     db
      PGSSLMODE:  disable
      PGUSER:     postgres
    image: jraspass/raku:toolbox
    tty: true
    volumes:
      - ..:/code-golf
    working_dir: /code-golf
  firefox:
    build:
      context: .
      dockerfile: firefox.Dockerfile
